image:
  - Visual Studio 2017

build_script:
  - set PATH=%PATH%;C:\Libraries\boost_1_67_0
  - echo %PATH%
  - build.bat -t local -B Release -i ..\ASNeG -vs "Ninja"
  - build.bat -t tst -B Release -s ASNeG -vs "Ninja"


