image:
  - Visual Studio 2017

build_script:
  - set BOOST_ROOT=C:\Libraries\boost_1_67_0
  - build.bat -t local -B Release -i .\ASNeG -vs "Visual Studio 15 2017 Win64"
  - build.bat -t tst -B Release -s .\ASNeG -vs "Visual Studio 15 2017 Win64"


