sudo: required
language: cpp

services:
  - docker

before_install:
  - docker build -t asneg/opcuastack:test .
  - docker run --name test_container asneg/opcuastack:test sh build.sh -t tst -j 2 -B Release
  - docker commit test_container asneg/opcuastack:test

script:
  - docker run -w /OpcUaStack/build_tst asneg/opcuastack:test ./OpcUaStackCoreTest
  - docker run -w /OpcUaStack/build_tst asneg/opcuastack:test ./OpcUaStackServerTest
  - docker run -w /OpcUaStack/build_tst asneg/opcuastack:test ./OpcUaStackClientTest
