sudo: required
language: cpp

services:
  - docker

before_install:
  - docker build -t asneg/opcuastack:test .
  - docker run --name test_container asneg/opcuastack:test build.sh -t tst
  - docker commit test_conatainer asneg/opcuastack:test

script:
  - docker run -w /OpcUaStack/build_tst asneg/opcuastack:test ./OpcUaStackCoreTest
  - docker run -w /OpcUaStack/build_tst asneg/opcuastack:test ./OpcUaStackServerTest
  - docker run -w /OpcUaStack/build_tst asneg/opcuastack:test ./OpcUaStackClientTest
