version: '2'
services:
  asneg-demo:
    image: asneg/asneg-demo:release-4
    hostname: asneg-demo
    volumes:
      - data-volume:/etc/OpcUaStack/ASNeG-Demo/pki
  stack:
    container_name: stack-${BUILD_TAG}
    depends_on:
      - asneg-demo
    hostname: asneg-test
    environment:
      - SERVER_PKI_ROOT_DIR=/tmp/
      - SERVER_HOST_NAME=asneg-demo
    build: .
    volumes:
      - data-volume:/OpcUaStack
      - data-volume:/tmp/etc/OpcUaStack/ASNeG-Demo/pki
volumes:
  data-volume:
