version: '2'
services:
  demo_server:
    image: asneg/asneg-demo:release-4
    hostname: asneg-demo
    ports:
      - 127.0.0.1:8889:8889
    volumes:
      - server_pki:/etc/OpcUaStack/ASNeG-Demo/pki
  stack:
    depends_on:
      - demo_server
    hostname: asneg-test
    environment:
      - SERVER_PKI_ROOT_DIR=/tmp/
      - SERVER_HOST_NAME=asneg-demo
    build: .
    volumes:
      - server_pki:/tmp/etc/OpcUaStack/ASNeG-Demo/pki
volumes:
  server_pki:
    driver: "local"
