version: '2'
services:
  demo_server:
    image: asneg/asneg-demo:latest
    ports:
      - 127.0.0.1:8889:8889
    volumes:
      - server_pki:/etc/OpcUaStack/ASNeG-Demo/pki
  stack:
    depends_on:
      - demo_server
    build: .
    volumes:
      - server_pki:/tmp/etc/OpcUaStack/ASNeG-Demo/pki
volumes:
  server_pki:
    driver: "local"
